with open('src/WaveManager.cpp', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('int WaveManager::GetTotalWaves() const {\n')
    f.write('    if (!stageData.contains("waves")) return 0;\n')
    f.write('    return stageData["waves"].size();\n')
    f.write('}\n')
    f.write('\n')
    f.write('int WaveManager::GetMaxBatchForWave(int waveId) const {\n')
    f.write('    if (!stageData.contains("waves")) return 0;\n')
    f.write('    for (const auto& w : stageData["waves"]) {\n')
    f.write('        if (w["wave_id"] == waveId) {\n')
    f.write('            if (!w.contains("batches")) return 0;\n')
    f.write('            int maxBatch = 0;\n')
    f.write('            for (const auto& b : w["batches"]) {\n')
    f.write('                int bId = b["batch_id"];\n')
    f.write('                if (bId > maxBatch) maxBatch = bId;\n')
    f.write('            }\n')
    f.write('            return maxBatch;\n')
    f.write('        }\n')
    f.write('    }\n')
    f.write('    return 0;\n')
    f.write('}\n')
